# Generated by Django 5.0.7 on 2024-07-23 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('picture', models.ImageField(upload_to='product_pictures/')),
                ('detail', models.TextField()),
                ('available_quantity', models.PositiveIntegerField()),
                ('category', models.CharField(choices=[('shoe', 'Shoe'), ('clothe', 'Clothe'), ('cap', 'Cap'), ('belt', 'Belt')], max_length=100)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_avaiable', models.BooleanField(default=False)),
            ],
        ),
    ]
