# Generated by Django 5.0.7 on 2024-07-23 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_avaiable',
            new_name='is_available',
        ),
    ]
