# Generated by Django 5.0.7 on 2024-07-29 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='user',
            new_name='vendor',
        ),
    ]
